name: ACE BAR Build and Deploy

on:
  push:
    branches:
      - main  # Or your working branch
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Pull IBM ACE 12 Image
      run: docker pull icr.io/ibm-appconnect/appconnect-12:latest

    - name: Build BAR using mqsipackagebar inside Container
      run: |
        mkdir -p bars
        docker run --rm \
          -v ${{ github.workspace }}:/app \
          icr.io/ibm-appconnect/appconnect-12:latest \
          bash -c "mqsipackagebar -a /app/bars/app.bar -w /app/workspace -k TestApp"

    - name: Commit BAR file to repo under 'bars/' folder
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git pull origin main  # Ensure latest changes
        git add bars/app.bar
        git commit -m 'Add packaged BAR file to bars/ directory'
        git push origin main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # Optional: Upload as GitHub artifact
    - name: Upload BAR as Artifact
      uses: actions/upload-artifact@v3
      with:
        name: app.bar
        path: bars/app.bar

    - name: Setup SSH for Dev Server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.DEV_SERVER }} >> ~/.ssh/known_hosts

    - name: Copy BAR to Dev Server
      run: scp bars/app.bar ${{ secrets.DEV_USER }}@${{ secrets.DEV_SERVER }}:/tmp/

    - name: Deploy BAR on Dev Server
      run: |
        ssh ${{ secrets.DEV_USER }}@${{ secrets.DEV_SERVER }} << EOF
          source /opt/ibm/ace-12/server/bin/mqsiprofile
          mqsibar -b /tmp -a app.bar -w /var/mqsi/components/DevIntegrationServer
        EOF
